/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg19630890;

import tabel.komputer;
import tabel.pelanggan;
import tabel.transaksi;

/**
 *
 * @author Windows 8.1
 */
public class flaporan extends javax.swing.JFrame {

    /**
     * Creates new form flaporan
     */
    public flaporan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        btransaksi = new javax.swing.JButton();
        bdaftarkomp = new javax.swing.JButton();
        bdaftarmember = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("LAPORAN");

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon("A:\\Kuliah\\PROJECT\\Sewa Pc\\Out-32.png")); // NOI18N
        jButton4.setText("KELUAR");
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btransaksi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btransaksi.setIcon(new javax.swing.ImageIcon("A:\\Kuliah\\PROJECT\\Sewa Pc\\Transaction-Fee-32.png")); // NOI18N
        btransaksi.setText("TRANSAKSI");
        btransaksi.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btransaksiActionPerformed(evt);
            }
        });

        bdaftarkomp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bdaftarkomp.setIcon(new javax.swing.ImageIcon("A:\\Kuliah\\PROJECT\\Sewa Pc\\Computer-Desktop-32.png")); // NOI18N
        bdaftarkomp.setText("DAFTAR KOMPUTER");
        bdaftarkomp.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        bdaftarkomp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdaftarkompActionPerformed(evt);
            }
        });

        bdaftarmember.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bdaftarmember.setIcon(new javax.swing.ImageIcon("A:\\Kuliah\\PROJECT\\Sewa Pc\\People-32.png")); // NOI18N
        bdaftarmember.setText("DAFTAR PELANGGAN");
        bdaftarmember.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        bdaftarmember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdaftarmemberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(bdaftarmember)
                    .addComponent(btransaksi)
                    .addComponent(bdaftarkomp)
                    .addComponent(jButton4)
                    .addComponent(jLabel1))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(btransaksi)
                .addGap(18, 18, 18)
                .addComponent(bdaftarkomp)
                .addGap(18, 18, 18)
                .addComponent(bdaftarmember)
                .addGap(40, 40, 40)
                .addComponent(jButton4)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btransaksiActionPerformed
        // TODO add your handling code here:
        new transaksi().setVisible(true);
    }//GEN-LAST:event_btransaksiActionPerformed

    private void bdaftarkompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdaftarkompActionPerformed
        // TODO add your handling code here:
        new komputer().setVisible(true);
    }//GEN-LAST:event_bdaftarkompActionPerformed

    private void bdaftarmemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdaftarmemberActionPerformed
        // TODO add your handling code here:
        new pelanggan().setVisible(true);
    }//GEN-LAST:event_bdaftarmemberActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(flaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(flaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(flaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(flaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new flaporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bdaftarkomp;
    private javax.swing.JButton bdaftarmember;
    private javax.swing.JButton btransaksi;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}


