/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg19630890;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.print.attribute.Size2DSyntax.MM;
import javax.swing.JOptionPane;
import javax.swing.JTable;
/**
 *
 * @author Windows 8.1
 */
public class ftransaksi extends javax.swing.JFrame {
 public int a,kali;
    
    private configdb db = new configdb();
    private String[] JudulKolom={"NO Transaksi","Tgl Transaksi","Nama User","Nama Komputer","mulai","selesai","Durasi","Total Bayar"};
    private int[]LebarKolom ={70,80,100,100,80,80,80,80};
    private String SQL="SELECT * FROM transaksi";
    
    public void tanggal(){
        Date ys=new Date();
        SimpleDateFormat s=new SimpleDateFormat("dd-MM-yyyy H:mm");
        tgl_transaksi.setText(s.format(ys));
    }
    public ftransaksi() {
        initComponents();
        this.setLocationRelativeTo(null);
        new configdb().setJudulTabel(tabel_transaksi, JudulKolom);
        new configdb().tampilTabel(tabel_transaksi, JudulKolom, SQL);
        new configdb().setLebarKolomTabel(tabel_transaksi, LebarKolom);
        tanggal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        notransaksi = new javax.swing.JTextField();
        tgl_transaksi = new javax.swing.JTextField();
        namauser = new javax.swing.JTextField();
        lamasewa = new javax.swing.JTextField();
        bsave = new javax.swing.JButton();
        bubah = new javax.swing.JButton();
        bbatal = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cari = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_transaksi = new javax.swing.JTable();
        bhapus = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        namakomp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tot = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tglmulai = new javax.swing.JFormattedTextField();
        tglselesai = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("TRANSAKSI");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("No Transaksi");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 74, -1, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Nama User");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Tanggal Transaksi");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Nama Komputer");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 155, -1, -1));

        notransaksi.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        notransaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(notransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 71, 255, -1));

        tgl_transaksi.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(tgl_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 100, 254, -1));

        namauser.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(namauser, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 126, 254, -1));

        lamasewa.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        lamasewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lamasewaActionPerformed(evt);
            }
        });
        getContentPane().add(lamasewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 240, 50, -1));

        bsave.setText("Save");
        bsave.setAlignmentY(0.0F);
        bsave.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        bsave.setIconTextGap(0);
        bsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsaveActionPerformed(evt);
            }
        });
        getContentPane().add(bsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 328, -1, -1));

        bubah.setText("Ubah");
        bubah.setAlignmentY(0.0F);
        bubah.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        bubah.setIconTextGap(0);
        bubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bubahActionPerformed(evt);
            }
        });
        getContentPane().add(bubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 328, -1, -1));

        bbatal.setText("Batal");
        bbatal.setAlignmentY(0.0F);
        bbatal.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        bbatal.setIconTextGap(0);
        bbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbatalActionPerformed(evt);
            }
        });
        getContentPane().add(bbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 328, -1, -1));

        jLabel6.setText("Cari Data");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 391, -1, -1));

        cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cariKeyReleased(evt);
            }
        });
        getContentPane().add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 388, 474, -1));

        tabel_transaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_transaksiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel_transaksi);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 414, 529, 130));

        bhapus.setText("Hapus");
        bhapus.setAlignmentY(0.0F);
        bhapus.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        bhapus.setIconTextGap(0);
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });
        getContentPane().add(bhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 328, -1, -1));

        keluar.setText("Keluar");
        keluar.setAlignmentY(0.0F);
        keluar.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        keluar.setIconTextGap(0);
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 328, -1, -1));

        namakomp.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(namakomp, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 152, 254, -1));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Tanggal Mulai");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 183, -1, -1));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Tanggal Selesai");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 213, -1, -1));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Durasi");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 243, -1, -1));

        tot.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totActionPerformed(evt);
            }
        });
        getContentPane().add(tot, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 255, -1));

        jLabel10.setText("Hari");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 243, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 51, 51));
        jLabel11.setText("*per hari 120.000");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 80, 20));

        tglmulai.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd-MM-yy"))));
        tglmulai.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(tglmulai, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 180, 254, -1));

        tglselesai.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd-MM-yy"))));
        tglselesai.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(tglselesai, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 210, 254, -1));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Bayar");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));

        jButton1.setText("Hitung");
        jButton1.setName("hitung"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        // TODO add your handling code here:
       String[] Fieldnya ={"no_transaksi","tanggal_transaksi","nama_user","nama_komputer","mulai","selesai","durasi","bayar"};
       String[] Valuenya = {notransaksi.getText(),tgl_transaksi.getText(),namauser.getText(),namakomp.getText(),tglmulai.getText(),tglselesai.getText(),lamasewa.getText(),tot.getText()};
       new configdb().Hapus("transaksi","no_transaksi",notransaksi.getText());
       JOptionPane.showMessageDialog(null,"Data Berhasil di Hapus");
       new configdb().setJudulTabel(tabel_transaksi, JudulKolom);
       new configdb().tampilTabel(tabel_transaksi, JudulKolom, SQL);
       new configdb().setLebarKolomTabel(tabel_transaksi, LebarKolom);
    }//GEN-LAST:event_bhapusActionPerformed

    private void bsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsaveActionPerformed
        // TODO add your handling code here:
       String[] Fieldnya ={"no_transaksi","tanggal_transaksi","nama_user","nama_komputer","mulai","selesai","durasi","bayar"};
       String[] Valuenya = {notransaksi.getText(),tgl_transaksi.getText(),namauser.getText(),namakomp.getText(),tglmulai.getText(),tglselesai.getText(),lamasewa.getText(),tot.getText()};
        if ( new configdb().DuplikasiPrimeryKey("transaksi","no_transaksi",notransaksi.getText()))
           {
            JOptionPane.showMessageDialog(null,"No Transaksi Sudah Ada");
           }else{
                 new configdb().Simpan("transaksi",Fieldnya, Valuenya);
                 JOptionPane.showMessageDialog(null,"Data Berhasil di Simpan");
                 new configdb().setJudulTabel(tabel_transaksi, JudulKolom);
                 new configdb().tampilTabel(tabel_transaksi, JudulKolom, SQL);
                 new configdb().setLebarKolomTabel(tabel_transaksi, LebarKolom);
                }
    }//GEN-LAST:event_bsaveActionPerformed

    private void bubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bubahActionPerformed
        // TODO add your handling code here:
       String[] Fieldnya ={"no_transaksi","tanggal_transaksi","nama_user","nama_komputer","mulai","selesai","durasi","bayar"};
       String[] Valuenya = {notransaksi.getText(),tgl_transaksi.getText(),namauser.getText(),namakomp.getText(),tglmulai.getText(),tglselesai.getText(),lamasewa.getText(),tot.getText()};
       new configdb().Ubah("transaksi","no_transaksi",notransaksi.getText(),Fieldnya, Valuenya);
       JOptionPane.showMessageDialog(null,"Data Berhasil di Ubah");
       new configdb().setJudulTabel(tabel_transaksi, JudulKolom);
       new configdb().tampilTabel(tabel_transaksi, JudulKolom, SQL);
       new configdb().setLebarKolomTabel(tabel_transaksi, LebarKolom); 
    }//GEN-LAST:event_bubahActionPerformed

    private void bbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbatalActionPerformed
        // TODO add your handling code here:
        notransaksi.setText("");
        namauser.setText("");
        namakomp.setText("");
        tglmulai.setText("");
        tglselesai.setText("");   
        lamasewa.setText("");
        tot.setText("");
        
    }//GEN-LAST:event_bbatalActionPerformed

    private void tabel_transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_transaksiMouseClicked
        // TODO add your handling code here:
        int row = tabel_transaksi.getSelectedRow();
        notransaksi.setText(tabel_transaksi.getModel().getValueAt(row,0).toString());
        namauser.setText(tabel_transaksi.getModel().getValueAt(row,2).toString());
        namakomp.setText(tabel_transaksi.getModel().getValueAt(row,3).toString());
        tglmulai.setText(tabel_transaksi.getModel().getValueAt(row,4).toString());
        tglselesai.setText(tabel_transaksi.getModel().getValueAt(row,5).toString());
        lamasewa.setText(tabel_transaksi.getModel().getValueAt(row,6).toString());
        tot.setText(tabel_transaksi.getModel().getValueAt(row,7).toString());
    }//GEN-LAST:event_tabel_transaksiMouseClicked

    private void cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariKeyReleased
        // TODO add your handling code here:
       String SQLCari ="SELECT * FROM transaksi WHERE no_transaksi LIKE'%"+cari.getText()+"%' OR nama_user LIKE '%"+cari.getText()+"%'";
       new configdb().setJudulTabel(tabel_transaksi, JudulKolom);
       new configdb().tampilTabel(tabel_transaksi, JudulKolom, SQLCari);
       new configdb().setLebarKolomTabel(tabel_transaksi, LebarKolom);
    }//GEN-LAST:event_cariKeyReleased

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_keluarActionPerformed

    private void totActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totActionPerformed
        // TODO add your handling code here:
    jButton1.getText();
    }//GEN-LAST:event_totActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        a = Integer.parseInt(lamasewa.getText());
        
        kali = a*120000;
    
        tot.setText(Integer.toString(kali)); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lamasewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lamasewaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lamasewaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ftransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ftransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ftransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ftransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ftransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbatal;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bsave;
    private javax.swing.JButton bubah;
    private javax.swing.JTextField cari;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField lamasewa;
    private javax.swing.JTextField namakomp;
    private javax.swing.JTextField namauser;
    private javax.swing.JTextField notransaksi;
    private javax.swing.JTable tabel_transaksi;
    private javax.swing.JTextField tgl_transaksi;
    private javax.swing.JFormattedTextField tglmulai;
    private javax.swing.JFormattedTextField tglselesai;
    private javax.swing.JTextField tot;
    // End of variables declaration//GEN-END:variables
}
